# In this directory, run the following command to build this builder.
# $ gcloud builds submit

substitutions:
  _DOCKER_20: DOCKER_VERSION=5:20.10.17~3-0~ubuntu-focal

steps:
# Pre-requisite: build the base OS container; 'temp' is referenced in the
# Dockerfile for subsequent steps but is not pushed. Building this shared base
# image enables the versioned builders to share base layers.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=temp'
  - '--file=Dockerfile-base'
  - '.'
  id: 'base'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/docker:latest'
  - '--tag=gcr.io/$PROJECT_ID/docker:20.10.17'
  - '--file=Dockerfile-versioned'
  - '--build-arg=${_DOCKER_20}'
  - '.'
  id: '20.10.17'
  wait_for: ['base']


- name: 'gcr.io/$PROJECT_ID/docker:20.10.17'
  args:
  - 'build'
  - '--file=Dockerfile-versioned'
  - '--build-arg=${_DOCKER_20}'
  - '.'
  wait_for: ['20.10.17']

# Tests for future supported versions of docker builder go here.

# Here are some things that can be done with this builder:

# Get info about an image. This effectively runs the "docker inspect" command on
# the image built above.
- name: 'gcr.io/$PROJECT_ID/docker'
  args: ['inspect', 'gcr.io/$PROJECT_ID/docker']
  wait_for: ['20.10.17']
# Execute a container. The "busybox" container is executed within the docker
# build step to echo "Hello, world!"
- name: 'gcr.io/$PROJECT_ID/docker'
  args: ['run', 'busybox', 'echo', 'Hello, world!']
  wait_for: ['20.10.17']

images:
- 'gcr.io/$PROJECT_ID/docker:latest'
- 'gcr.io/$PROJECT_ID/docker:20.10.17'

timeout: 1200s
